RF AT_03.02.005 User is redirected to correct page
RedRoverSchool/JenkinsQA_JS_06 pull request #1030
Opened 2023-07-21 12:21 UTC by Julia-Cherniak

https://trello.com/c/0ypIat3V/1947-rf-at0302005-footer-verify-user-is-redirected-to-the-correct-page-after-clicking-the-link-jenkins

2023-07-21 15:16 UTC, IrynaKolh reviewed
возможно вам следует удалить AT_03.02_008 как дубликат, так как в жтом тесте вы проверяете и url и header

2023-07-21 15:29 UTC, IrynaKolh reviewed
номер катрочки должен иметь вид AT_03.02.05

2023-07-21 17:24 UTC, Rom-T approved these changes

2023-07-21 17:27 UTC, Rom-T reviewed
Измени

2023-07-21 17:27 UTC, Rom-T commented on cypress/pageObjects/JenkinsPage.js
> +        cy.url().should('equal', link);
Здесь используйте уже созданный элемент   `getJenkinsPageUrl.should('equal', link);`

2023-07-21 17:30 UTC, Rom-T requested changes
Да, необходимо удалить этот тест и добавить проверку на url в тест AT_03.02_008

2023-07-21 19:46 UTC, Julia-Cherniak commented
Да, у меня в US два похожих теста, один кликает по Jenkins 2.387.2 и проверяет cy.url, другой проверяет "have text", поэтому я этот решила переделать и добавить в него проверку "have text" из AT_03.02_008, и последний я хочу удалить. Я уже даже карточку RF создала, только хотела его удалить после того как этот добавляют в мэйн.

2023-07-21 19:54 UTC, Julia-Cherniak commented on cypress/pageObjects/JenkinsPage.js
> +        cy.url().should('equal', link);
изменила

2023-07-22 00:07 UTC, Rom-T approved these changes

2023-07-22 07:00 UTC, merged