AT_04.02.15 | <Breadcrumbs> Clicking on the Dashboard page link is redirected to the Jenkins home page
RedRoverSchool/JenkinsQA_JS_06 pull request #1114
Opened 2023-08-05 00:45 UTC by nadya0101

https://trello.com/c/SJErEljV/2107-at040215-breadcrumbs-clicking-on-the-dashboard-page-link-is-redirected-to-the-jenkins-home-page

2023-08-05 01:41 UTC, verafes approved these changes

2023-08-05 03:17 UTC, Rom-T requested changes

2023-08-05 03:17 UTC, Rom-T commented on .vscode/settings.json
> +    "git-blame.gitWebUrl": ""
а зачем вы добавили данную строку в конфигурационный файл?

2023-08-05 08:26 UTC, nadya0101 commented on .vscode/settings.json
> +    "git-blame.gitWebUrl": ""
Поман, я ничего не добавляла. Но git-blame нам советовали поставить у себя, я его ставила. И думала, что он остался только у меня. Как я могу исправить то, что сделано неправильно? Как-то могу отменить?

2023-08-05 15:16 UTC, Rom-T commented on .vscode/settings.json
> +    "git-blame.gitWebUrl": ""
Да, удалите эту строку и запушите снова.

2023-08-05 21:46 UTC, nadya0101 commented on .vscode/settings.json
> +    "git-blame.gitWebUrl": ""
Done and thanks a lot!

2023-08-05 21:59 UTC, SiarheiMSV approved these changes

2023-08-07 19:55 UTC, Rom-T approved these changes

2023-08-07 20:46 UTC, merged