AT_01.02_005 | Verify Search box is accessible from every page on the header
RedRoverSchool/JenkinsQA_JS_06 pull request #120
Opened 2023-05-13 04:52 UTC by Olga-QA-USA

https://trello.com/c/XpsLdXN6/227-at0102005-verify-search-box-is-accessible-from-every-page-on-the-header

2023-05-14 10:55 UTC, nadya0101 approved these changes

2023-05-14 15:07 UTC, Forostinko commented
You need to do 1 branch = 1 it

2023-05-14 17:36 UTC, MariaMoroz requested changes
Один пиар = 1 тест = 1 задача!

2023-05-15 04:03 UTC, Olga-QA-USA commented
> Один пиар = 1 тест = 1 задача!

спасибо, исправила.

2023-05-15 17:59 UTC, merged