AT_13.04 | <Pipeline> Add description to the pipeline < testAddDescriptionPipeline
RedRoverSchool/JenkinsQA_JS_06 pull request #220
Opened 2023-05-16 08:33 UTC by ElNov686

[AT] - https://trello.com/c/EpbrQZT1/332-at1304-pipeline-add-description-to-the-pipeline-testadddescriptionpipeline

2023-05-16 14:53 UTC, ArinaJur requested changes

2023-05-16 14:53 UTC, ArinaJur commented on cypress/e2e/pipelineToAddDescription.cy.js
> +describe('Add a description to the Pipeline', () => {
Please change description name to your cy.js file name
describe('pipelineToAddDescription', () => {

2023-05-17 11:52 UTC, NatalyaVasylyeva commented
1. You should change Number of TC, AT in Trello and in other places (PR, it) - add number of you test case to a number of User Story: TC_US_13.04_№№№.
2. You should put CONST into "it"
3. You should make link to your PR to AT card it Trello

2023-05-21 18:43 UTC, ElNov686 commented on cypress/e2e/pipelineToAddDescription.cy.js
> +describe('Add a description to the Pipeline', () => {
done, thank you!

2023-05-23 13:50 UTC, closed without merging