[RF] Homepage (Dashboard)|User is able to add and edit the text in the panel description
RedRoverSchool/JenkinsQA_JS_06 pull request #229
Opened 2023-05-16 14:54 UTC by IrynaKolyada

https://trello.com/c/qaRBBcbP/612-rf-homepage-dashboarduser-is-able-to-add-and-edit-the-text-in-the-panel-description

2023-05-16 15:20 UTC, ArinaJur requested changes

2023-05-16 15:28 UTC, IrynaKolyada commented on cypress/e2e/add_description.cy.js
> +describe('US_02.06 | Homepage (Dashboard) > Verify the Main panel description', ()=>{
@ArinaJur Irina I am not sure that I got  what you meant.  I thought I do everything as requested. Please give me an example of another test and i will take a look at it. Thanks a lot.

2023-05-16 18:46 UTC, IrynaKolyada commented on cypress/e2e/add_description.cy.js
> +describe('US_02.06 | Homepage (Dashboard) > Verify the Main panel description', ()=>{
All done. Please review

2023-05-16 18:47 UTC, ArinaJur commented on cypress/e2e/add_description.cy.js
> +describe('US_02.06 | Homepage (Dashboard) > Verify the Main panel description', ()=>{
Please check the thread in Slack, and watch yesterday's lesson. 
From Maria's presentation: "describe  содержит в точности название файла"

2023-05-16 18:51 UTC, ArinaJur requested changes

2023-05-16 18:51 UTC, ArinaJur commented on cypress/e2e/add_description.cy.js
> +describe('US_02.06 | Homepage Dashboard_Verify the Main panel description', ()=>{
Please change to 
describe ('add_description', () => {

According to yesterday's lesson. We should put the file name to describe

2023-05-16 19:48 UTC, IrynaKolyada commented on cypress/e2e/add_description.cy.js
> +describe('US_02.06 | Homepage (Dashboard) > Verify the Main panel description', ()=>{
@ArinaJur  I misunderstood.  all done . Thank you

2023-05-17 01:12 UTC, IrynaKolyada commented on cypress/e2e/add_description.cy.js
> +describe('US_02.06 | Homepage Dashboard_Verify the Main panel description', ()=>{
All done

2023-05-17 02:05 UTC, ArinaJur approved these changes

2023-05-17 02:08 UTC, Olga-Khliupina approved these changes

2023-05-17 02:09 UTC, merged