AT_12.03.0012 Rename project, new name is valid
RedRoverSchool/JenkinsQA_JS_06 pull request #231
Opened 2023-05-16 16:54 UTC by KaterinaNa

2023-05-17 20:33 UTC, elviraKh1 requested changes

2023-05-17 20:33 UTC, elviraKh1 commented on cypress/e2e/renameFreestyleProject invalid.cy.js
> +describe('Freestyle project  Rename project', () => {
- имя файла пишем без пробелов (запрос на изменения PR  из за названия файлов)
- describe должен содержать название файла  renameFreestyleProject invalid, 
- в одном PR один тест

2023-05-17 20:33 UTC, elviraKh1 commented on cypress/e2e/renameFreestyleProject invalid.cy.js
> +      cy.get('div#main-panel p').contains(fullErrorMessage);
если переменная используется один раз, то нет необходимости делать ее глобальной на все it

2023-05-18 21:28 UTC, elviraKh1 commented on cypress/e2e/renameFreestyleProject_valid.cy.js
> +      cy.get('div h1').contains(newProjectName);
к сожалению строка 29 не является ассертом, 
https://docs.cypress.io/guides/references/assertions здесь подробнее

2023-05-18 21:28 UTC, elviraKh1 commented on cypress/e2e/renameFreestyleProject_valid.cy.js
> +      cy.get('input[name="newName"]').clear().type(newProjectName);
сделайте пожалуйста отступы, правильное форматирование необходимо.

2023-05-18 21:34 UTC, elviraKh1 commented on cypress/e2e/renameFreestyleProject_valid.cy.js
> +      cy.get('input[name="newName"]').clear().type(newProjectName);
так же нужна ссылка на трелло

2023-05-18 21:37 UTC, elviraKh1 commented on cypress/e2e/renameFreestyleProject_valid.cy.js
> +      cy.get('input[name="newName"]').clear().type(newProjectName);
в имени файла используется camelCase (нижнее подчеркивание не уверена , что хорошая практика)

2023-05-18 22:45 UTC, MariaMoroz reviewed
забыли прикрепить карточку из трелло

2023-05-19 13:25 UTC, KaterinaNa commented
https://trello.com/c/ObwuDEbu/619-at1203012-rename-project-new-name-is-valid

2023-05-19 17:39 UTC, elviraKh1 approved these changes

2023-05-20 02:20 UTC, Rom-T commented on cypress/e2e/renameFreestyleProjectValid.cy.js
> +    let newProjectName = "AnotherProject";
Please move `data` in the fixtures

2023-05-20 02:20 UTC, Rom-T commented on cypress/e2e/renameFreestyleProjectValid.cy.js
> +      cy.get('#ok-button').should('have.text', 'OK').click();
Please move `OK` in the fixtures

2023-05-20 02:20 UTC, Rom-T commented on cypress/e2e/renameFreestyleProjectValid.cy.js
> +      cy.get('.setting-main  textarea  ').eq(0).type('test');
Please move `test` in the fixtures

2023-05-20 08:17 UTC, KaterinaNa commented on cypress/e2e/renameFreestyleProjectValid.cy.js
> +      cy.get('.setting-main  textarea  ').eq(0).type('test');
Простите, Rom_T, в переписке выше я вносила исправления в свой тест в том числе по причине того, что необходимо было убрать переменные, тк они используются 1 раз.

2023-05-20 19:17 UTC, Rom-T approved these changes

2023-05-20 20:12 UTC, merged