AT_01.02.18 | <Header> Search box
RedRoverSchool/JenkinsQA_JS_06 pull request #278
Opened 2023-05-17 16:22 UTC by Olgalex

2023-05-17 20:23 UTC, elviraKh1 commented on cypress/e2e/searchBoxPlaceholder.cy.js
> +it ('01.02 | <Header> Search box',() => {
Убираем из описания it знаки <, > и добавьте ссылку на Трелло

2023-05-17 22:36 UTC, DariaMas7 commented on cypress/e2e/searchBoxPlaceholder.cy.js
> +it ('01.02 | <Header> Search box',() => {
Also you should format your document

2023-05-18 12:41 UTC, Olgalex commented
https://trello.com/c/vRPfk6nn/697-at010218-header-search-box

2023-05-18 17:05 UTC, 7108581 commented
Your test case should correspond with AT. You have 3 expected results in TC, but only 1 assertion in automation It. I suggest you change TC by leaving there only one expected result. Then you can write another TC and automate it.

2023-05-18 17:06 UTC, 7108581 approved these changes

2023-05-18 17:41 UTC, IrynaKolh requested changes

2023-05-18 17:41 UTC, IrynaKolh commented on cypress/e2e/searchBoxPlaceholder.cy.js
> +    it('AT_01.02.18_Header_Search_box', () => {
Ваш ТС уже 18, значит есть  файл где другие участники добавили код => headerSeachBox.cy.js куда и вас следует дописать свой код, а не создать новый файл

2023-05-18 17:42 UTC, IrynaKolh commented on cypress/e2e/searchBoxPlaceholder.cy.js
> +    it('AT_01.02.18_Header_Search_box', () => {
В описании ПР нужно дать ссылку на ваш АТ, а не в коментах

2023-05-18 17:45 UTC, IrynaKolh commented on cypress/e2e/searchBoxPlaceholder.cy.js
> +    it('AT_01.02.18_Header_Search_box', () => {
Ваш тест не делает ничего из заявленого в ТС 
```
Expecting results:
Search box is found on the top right of the header - вы не проверяете его положение
It is accessible from every page - вы не проверяете что он на всех станицах, только на 1 (нужно тогда указать на какой)
It is case insensitive by default 
```
Ваш тест проверяет его плейсхолдер

2023-05-19 11:57 UTC, IrynaKolh approved these changes

2023-05-19 12:33 UTC, merged