Msv/check search box
RedRoverSchool/JenkinsQA_JS_06 pull request #44
Opened 2023-05-11 16:21 UTC by SiarheiMSV

https://trello.com/c/YGyDbesy/135-at0102002-check-placeholder-text-search-ctrlk

2023-05-11 16:44 UTC, shablouskaya approved these changes

2023-05-11 22:22 UTC, IharStankevich approved these changes

2023-05-13 01:07 UTC, MariaMoroz requested changes
Не могу пропустить пиар, в котором удаляются чужие тесты

2023-05-13 04:53 UTC, SiarheiMSV commented
Мария, а можете удалить этот пиар вообще? Просто я не могу понять как его
поменять( ветку я уже эту удалил и как что то там поменять я не имею
понятия)


On Fri, May 12, 2023 at 21:07 MariaMoroz ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Не могу пропустить пиар, в котором удаляются чужие тесты
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RedRoverSchool/JenkinsQA_JS_06/pull/44#pullrequestreview-1425296967>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZP4NXSRLRMIP4QF7IVUQZDXF3NELANCNFSM6AAAAAAX6LT2XM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-13 14:12 UTC, closed without merging