AT_18.05_002 Profile Page> dashboard  My view link
RedRoverSchool/JenkinsQA_JS_06 pull request #595
Opened 2023-05-25 03:27 UTC by Kseniyaza

https://trello.com/c/vDVQXVPA/1020-at1805002-profile-page-open-dashboard-with-my-view-link

2023-05-25 05:14 UTC, Rom-T commented on cypress/e2e/profilePageOpenDashboardWithMyViewLink.cy.js
> +describe('KZ-profilePageOpenDashboardMyViewLink.cy.js', () => {
Please name the describe as the name of your file.

2023-05-25 05:14 UTC, Rom-T commented on cypress/e2e/profilePageOpenDashboardWithMyViewLink.cy.js
> +    ];
Please move `data` in the fixtures

2023-05-25 06:28 UTC, DariaMas7 reviewed
Its better to write your code in already existing file for this US 
profilePageOpenDashboardMyViewLink.cy

2023-05-25 06:28 UTC, DariaMas7 commented on cypress/e2e/profilePageOpenDashboardWithMyViewLink.cy.js
> +
please delete all of the empty lines we don't need them

2023-05-25 18:58 UTC, Rom-T commented on cypress/e2e/profilePageOpenDashboardWithMyViewLink.cy.js
> +        cy.get('a[href="/view/all/newJob"]')
This line does nothing. Please delete it.

2023-06-20 09:47 UTC, SvetlanaVet approved these changes

2023-06-24 19:33 UTC, SawkaQA approved these changes

2023-07-06 02:03 UTC, Rom-T requested changes
Close please PR

2023-07-10 16:43 UTC, closed without merging