Header, Head Icon is visible and redirects
RedRoverSchool/JenkinsQA_JS_06 pull request #664
Opened 2023-05-29 17:37 UTC by DaryaAndrosova

https://trello.com/c/6DNfNp7M

2023-05-29 19:54 UTC, matvlesia reviewed
Hi, text 'Welcome to Jenkins!' should be moved to fixtures

2023-05-30 00:41 UTC, Rom-T commented on cypress/e2e/headerHeadIcon.cy.js
> +        cy.get('div h1').should('include.text', 'Welcome to Jenkins!');
Please move `Welcome to Jenkins!` in the fixtures

2023-05-30 15:12 UTC, NatalyaVasylyeva commented
Hi! The name of your PullRequest should be the same as your AT card

2023-06-13 16:33 UTC, Forostinko commented on cypress/e2e/headerHeadIcon.cy.js
> +        cy.get('[href="/asynchPeople/"]').click();
should be added to the fixtures

2023-06-13 16:34 UTC, Forostinko commented on cypress/e2e/headerHeadIcon.cy.js
> +        cy.get('#jenkins-head-icon').click();
same

2023-06-17 11:16 UTC, SvetlanaVet approved these changes

2023-06-22 15:51 UTC, Forostinko commented on cypress/e2e/headerHeadIcon.cy.js
> +        cy.get('#jenkins-head-icon').click();
Here same

2023-06-24 19:32 UTC, SawkaQA approved these changes

2023-07-06 02:02 UTC, Rom-T requested changes
Close please PR

2023-07-10 16:43 UTC, closed without merging